const Allproduct = [
    {
        id: 1,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Engine Oil",
        image: './Photo/image.png',
        new_price: 20.00,
        old_price: 30.00,
        category: "oil",
        size: "1 Liter",
        image2: "./Photo/image.webp",
    },
    {
        id: 2,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Battery",
        image: './Photo/image.png',
        new_price: 50.00,
        old_price: 70.00,
        category: "battery",
        size: "Standard Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 3,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Air Filter",
        image: './Photo/image.png',
        new_price: 15.00,
        old_price: 25.00,
        category: "filter",
        size: "Standard Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 4,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Clutch Cable",
        image: './Photo/image.png',
        new_price: 10.00,
        old_price: 15.00,
        category: "cable",
        size: "Standard Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 5,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Front Brake Shoe",
        image: './Photo/image.png',
        new_price: 12.00,
        old_price: 20.00,
        category: "brakes",
        size: "Standard Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 6,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Rear Brake Shoe",
        image: './Photo/image.png',
        new_price: 12.00,
        old_price: 20.00,
        category: "brakes",
        size: "Standard Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 7,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Spark Plug",
        image: './Photo/image.png',
        new_price: 5.00,
        old_price: 10.00,
        category: "spark plug",
        size: "Standard Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 8,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Oil Filter",
        image: './Photo/image.png',
        new_price: 8.00,
        old_price: 12.00,
        category: "filter",
        size: "Standard Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 9,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Chain",
        image: './Photo/image.png',
        new_price: 25.00,
        old_price: 35.00,
        category: "chain",
        size: "Standard Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 10,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Muffler",
        image: './Photo/image.png',
        new_price: 30.00,
        old_price: 45.00,
        category: "exhaust",
        size: "Standard Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 11,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Shock Absorber",
        image: './Photo/image.png',
        new_price: 45.00,
        old_price: 60.00,
        category: "suspension",
        size: "Standard Shock Absorber Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 12,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Speedometer",
        image: './Photo/image.png',
        new_price: 55.00,
        old_price: 70.00,
        category: "accessories",
        size: "Standard Speedometer Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 13,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Foot Pegs",
        image: './Photo/image.png',
        new_price: 15.00,
        old_price: 25.00,
        category: "foot pegs",
        size: "Standard Foot Peg Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 14,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Horn",
        image: './Photo/image.png',
        new_price: 20.00,
        old_price: 30.00,
        category: "accessories",
        size: "Standard Horn Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 15,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Rear View Mirror",
        image: './Photo/image.png',
        new_price: 10.00,
        old_price: 15.00,
        category: "accessories",
        size: "Standard Mirror Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 16,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Starter Relay",
        image: './Photo/image.png',
        new_price: 35.00,
        old_price: 50.00,
        category: "electrical",
        size: "Standard Relay Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 17,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Voltage Regulator",
        image: './Photo/image.png',
        new_price: 40.00,
        old_price: 55.00,
        category: "electrical",
        size: "Standard Regulator Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 18,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Carburetor",
        image: './Photo/image.png',
        new_price: 65.00,
        old_price: 90.00,
        category: "engine",
        size: "Standard Carburetor Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 19,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Chain Cover",
        image: './Photo/image.png',
        new_price: 30.00,
        old_price: 40.00,
        category: "body",
        size: "Standard Chain Cover Size",
        image2: "./Photo/image.webp",
    },
    {
        id: 20,
        title: 'Al Shams Honda Center',
        name: "Honda CG 125 Kick Starter",
        image: './Photo/image.png',
        new_price: 25.00,
        old_price: 35.00,
        category: "engine",
        size: "Standard Kick Starter Size",
        image2: "./Photo/image.webp",
    }
];

export default Allproduct

